name: movie_rada_n
description: "where u find ur favourite movies"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_color_utilities: 0.11.1
  http: ^1.4.0
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.3.0
  provider: ^6.1.2
  leak_tracker: ^10.0.8
  rxdart: ^0.28.0
  vector_math: 2.1.4
  vm_service: 14.3.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.11
#  sqflite_common_ffi: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2
  lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  image_path: assets/images/icon.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: assets/images/icon.png
  image_path: assets/images/icon.png
